name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Compilar no JAVA
      run: mvn compile
      
    - name: Run Program - Java
      run: java -cp target/classes org.example.Main
    
    - name: Calculando 
      id: calculo
      run: |
         echo "::set-output name=version_new::$(echo $((${{ github.run_number }}/10)))"
  
    #- name: Git Version
    #  id: gerador
    #  uses: codacy/git-version@2.4.0
    #  with:
        # The name of the release branch
    #    release-branch: master
        # The prefix to use in the version
    #    prefix: QA-

    #- name: Use the version
    #  run: |
    #      echo ${{ steps.gerador.outputs.version }}
    #- name: Use the previous version
    #  run: |
    #      echo ${{ steps.gerador.outputs.previous-version }}
   
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image
      with:
          image: nisflei/aula_maven_f
          tags: ${{ github.run_number }}, ${{ steps.gerador.outputs.version }}, ${{ steps.calculo.outputs.version_new }}
          registry: docker.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
