name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Compilar no JAVA
      run: mvn compile
      
    - name: Run Program - Java
      run: java -cp target/classes org.example.Main
    
   # - name: Calculando 
   #   id: calculo
   #   run: |
   #      echo "::set-output name=version_new::$(echo ${{ github.run_number }}/10)"
      
    - name: Get & Manipulate Git Version
      uses: maxkruger/get-version-action@v3.0.3
    - run: echo ${{ steps.get_version.outputs.version }}
    - run: echo ${{ steps.get_version.outputs.version-without-v }}
   
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image
      with:
          image: nisflei/aula_maven_f
          tags: ${{ github.run_number }}
          registry: docker.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
